import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'overview',
    'quick_start',
    {
      type: 'category',
      label: 'Tutorial',
      items: [
        {
          type: 'doc',
          id: 'tutorial/overview'
        },
        {
          type: 'doc',
          id: 'tutorial/open_nutsdb'
        },,
        {
          type: 'doc',
          id: 'tutorial/options'
        },
        {
          type: 'doc',
          id: 'tutorial/transaction'
        },
        {
          type: 'doc',
          id: 'tutorial/kv'
        },
        {
          type: 'doc',
          id: 'tutorial/list'
        },
        {
          type: 'doc',
          id: 'tutorial/set'
        },
        {
          type: 'doc',
          id: 'tutorial/sorted_set'
        },
      ],
    },
    'compare',
    'benchmark'
  ],

  releaseNotesSidebar: [
    {type: 'autogenerated', dirName: './release_notes'},
  ]
};

export default sidebars;
